const EMPLOYEES = [
  {
    id: "1",
    name: "Mark Hill",
    designation: "Chief Executive Officer",
    team: "Executive",
    managerId: null,
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: "2",
    name: "Joe Linux",
    designation: "Chief Technology Officer",
    team: "Technology",
    managerId: "1",
    image: "https://randomuser.me/api/portraits/men/53.jpg",
  },
  {
    id: "3",
    name: "Linda May",
    designation: "Chief Business Officer",
    team: "Business",
    managerId: "1",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
  },
  {
    id: "4",
    name: "Ron Blomquist",
    designation: "Chief Information Security Officer",
    team: "Technology",
    managerId: "2",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: "5",
    name: "Alice Lopez",
    designation: "Chief Communications Officer",
    team: "Business",
    managerId: "3",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: "6",
    name: "Michael Rubin",
    designation: "Chief Innovation Officer",
    team: "Technology",
    managerId: "2",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: "7",
    name: "Mary Johnson",
    designation: "Chief Brand Officer",
    team: "Business",
    managerId: "3",
    image: "https://randomuser.me/api/portraits/women/70.jpg",
  },
  {
    id: "8",
    name: "Kirk Douglas",
    designation: "Chief Business Development Officer",
    team: "Business",
    managerId: "3",
    image: "https://randomuser.me/api/portraits/men/91.jpg",
  },
  {
    id: "9",
    name: "John Green",
    designation: "Chief Accounting Officer",
    team: "Accounts",
    managerId: "1",
    image: "https://randomuser.me/api/portraits/men/60.jpg",
  },
  {
    id: "10",
    name: "Erica Reel",
    designation: "Chief Customer Officer",
    team: "Accounts",
    managerId: "3",
    image: "https://randomuser.me/api/portraits/women/67.jpg",
  },
];

export { EMPLOYEES };
